window.updateList = [
    //app文件夹
    'app/index.js',
    'app/menu.js',
    'app/redirect.js',
    'app/color.css',
    'app/index.css',
    //'app/xinwei.ttf',

    'downloadExtension.html',
    'main.js',
    'update.html',
    'app.html',

    //教程
    //'doc/(必看)无名杀全教程10.0.pdf',

	//搬运自用
    'NoName/extension/搬运自用/extension.js',
	
    //应用配置
    'NoName/extension/应用配置/extension.js',
    'NoName/extension/应用配置/extension_demo.js',
    'NoName/extension/应用配置/export.js',
    'NoName/extension/应用配置/api.js',
    'NoName/extension/应用配置/highlightjs-line-numbers.min.js',

    //在线更新
    'NoName/extension/在线更新/extension.js',
	'NoName/extension/在线更新/extension.css',
	'NoName/extension/在线更新/typings/index.d.ts',

    //拖拽读取
    'NoName/extension/拖拽读取/extension.css',
    'NoName/extension/拖拽读取/extension.js',
    'NoName/extension/拖拽读取/jszip.js',
    'NoName/extension/拖拽读取/minizip-asm.min.js',
    'NoName/extension/拖拽读取/version',
    'NoName/extension/拖拽读取/worker.js',
    'NoName/extension/拖拽读取/catalogTemplate.txt',
    'NoName/extension/拖拽读取/README.md',
    'NoName/extension/拖拽读取/node_modules/iconv-lite/Changelog.md',
    'NoName/extension/拖拽读取/node_modules/iconv-lite/LICENSE',
    'NoName/extension/拖拽读取/node_modules/iconv-lite/package.json',
    'NoName/extension/拖拽读取/node_modules/iconv-lite/README.md',
    'NoName/extension/拖拽读取/node_modules/iconv-lite/encodings/dbcs-codec.js',
    'NoName/extension/拖拽读取/node_modules/iconv-lite/encodings/dbcs-data.js',
    'NoName/extension/拖拽读取/node_modules/iconv-lite/encodings/index.js',
    'NoName/extension/拖拽读取/node_modules/iconv-lite/encodings/internal.js',
    'NoName/extension/拖拽读取/node_modules/iconv-lite/encodings/sbcs-codec.js',
    'NoName/extension/拖拽读取/node_modules/iconv-lite/encodings/sbcs-data-generated.js',
    'NoName/extension/拖拽读取/node_modules/iconv-lite/encodings/sbcs-data.js',
    'NoName/extension/拖拽读取/node_modules/iconv-lite/encodings/utf16.js',
    'NoName/extension/拖拽读取/node_modules/iconv-lite/encodings/utf32.js',
    'NoName/extension/拖拽读取/node_modules/iconv-lite/encodings/utf7.js',
    'NoName/extension/拖拽读取/node_modules/iconv-lite/encodings/tables/big5-added.json',
    'NoName/extension/拖拽读取/node_modules/iconv-lite/encodings/tables/cp936.json',
    'NoName/extension/拖拽读取/node_modules/iconv-lite/encodings/tables/cp949.json',
    'NoName/extension/拖拽读取/node_modules/iconv-lite/encodings/tables/cp950.json',
    'NoName/extension/拖拽读取/node_modules/iconv-lite/encodings/tables/eucjp.json',
    'NoName/extension/拖拽读取/node_modules/iconv-lite/encodings/tables/gb18030-ranges.json',
    'NoName/extension/拖拽读取/node_modules/iconv-lite/encodings/tables/gbk-added.json',
    'NoName/extension/拖拽读取/node_modules/iconv-lite/encodings/tables/shiftjis.json',
    'NoName/extension/拖拽读取/node_modules/iconv-lite/lib/bom-handling.js',
    'NoName/extension/拖拽读取/node_modules/iconv-lite/lib/index.d.ts',
    'NoName/extension/拖拽读取/node_modules/iconv-lite/lib/index.js',
    'NoName/extension/拖拽读取/node_modules/iconv-lite/lib/streams.js',
    'NoName/extension/拖拽读取/node_modules/safer-buffer/dangerous.js',
    'NoName/extension/拖拽读取/node_modules/safer-buffer/LICENSE',
    'NoName/extension/拖拽读取/node_modules/safer-buffer/package.json',
    'NoName/extension/拖拽读取/node_modules/safer-buffer/Porting-Buffer.md',
    'NoName/extension/拖拽读取/node_modules/safer-buffer/Readme.md',
    'NoName/extension/拖拽读取/node_modules/safer-buffer/safer.js',
    'NoName/extension/拖拽读取/node_modules/safer-buffer/tests.js',
    

    // typings
    "typings/ai.d.ts",
    "typings/AIConfig.d.ts",
    "typings/ArrayEx.d.ts",
    "typings/brawl.d.ts",
    "typings/button.d.ts",
    "typings/card.d.ts",
    "typings/CardConfig.d.ts",
    "typings/CharacterConfig.d.ts",
    "typings/cheat.d.ts",
    "typings/click.d.ts",
    "typings/client.d.ts",
    "typings/content.d.ts",
    "typings/control.d.ts",
	"typings/cordova-plugin-dialogs.d.ts",
    "typings/cordova-plugin-file.d.ts",
	"typings/cordova-plugin-file-transfer.d.ts",
	"typings/cordova-plugin-local-notifications.d.ts",
    "typings/cordova.d.ts",
    "typings/create.d.ts",
    "typings/DateEx.d.ts",
    "typings/develop.d.ts",
    "typings/dialog.d.ts",
    "typings/electron.d.ts",
    "typings/event.d.ts",
    "typings/ExInterface.d.ts",
    "typings/ExtensionConfig.d.ts",
    "typings/filter.d.ts",
    "typings/game.d.ts",
    "typings/get.d.ts",
    "typings/HTMLDivElementEx.d.ts",
    "typings/import-card.d.ts",
    "typings/import-character.d.ts",
    "typings/index.d.ts",
    "typings/init.d.ts",
    "typings/lib.d.ts",
    "typings/LocalGameConfigMenu.d.ts",
    "typings/message.d.ts",
    "typings/nodews.d.ts",
    "typings/player.d.ts",
    "typings/SkillConfig.d.ts",
    "typings/sort.d.ts",
    "typings/status.d.ts",
    "typings/type.d.ts",
    "typings/ui.d.ts",
    "typings/windowEx.d.ts",
    "typings/ws.d.ts",
	
	//放置最后更新 防止中断被误认更新完毕
	//'package-lock.json',
	'package.json'
];

window.removeFileList = [
    //教程
    //'(必看)无名杀全教程9.5.pdf',
    //'(必看)无名杀全教程9.6.pdf',
    //'(必看)无名杀全教程9.7.pdf',
    //'(必看)无名杀全教程9.8.pdf',
    //'(必看)无名杀全教程9.9.pdf'
];